name: Build ROM

on:
  workflow_dispatch:
  push:
    branches:
      - heroku
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Update packages and install dependencies
        run: |
          if curl -fsSL --connect-timeout 5 https://www.google.com >/dev/null; then
              echo "Internet available"
          else
              echo "No internet"
          fi
