name: QuantumROM Tools

on:
  push:
    branches:
      - heroku

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          blkid odm.img
          ls
          pwd
          sudo cp -v "./bin/erofs-utils/*" "/usr/local/bin/"
          sudo chmod 755 "/usr/local/bin/*"
          extract.erofs
